---
abstract: 'AnyEvent MXHR Client'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  AnyEvent::Socket: 0
  ExtUtils::MakeMaker: 6.36
  JSON: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-HTTP-MXHR
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 6.01
  AnyEvent::HTTP: 0
  AnyEvent::Handle: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00007
